name: "samtools_index"
description: Index BAM files for fast random access
keywords:
  - index
  - bam
  - bai
  - samtools
tools:
  - samtools:
      description: |
        SAMtools is a suite of programs for interacting with high-throughput sequencing data.
        It consists of three separate repositories: Samtools (reading/writing/editing/indexing/viewing SAM/BAM/CRAM format),
        BCFtools (reading/writing BCF2/VCF/gVCF files and calling/filtering/summarising SNP and short indel sequence variants),
        and HTSlib (a C library for reading/writing high-throughput sequencing data formats).
      homepage: http://www.htslib.org/
      documentation: https://www.htslib.org/doc/samtools-index.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - bam:
      type: file
      description: BAM file to index
      pattern: "*.bam"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - bai:
      type: file
      description: BAM index file
      pattern: "*.bai"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@bhargava-morampalli"
