channels:
  - anaconda
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python>=3.8
  - numpy
  - scipy
  - pandas
  - seaborn
  - pysam
  - biopython
  - matplotlib
  - statsmodels
  - samtools=1.17
  - bedtools
  - git
  - pip
  - pip:
      - git+https://github.com/DepledgeLab/DRUMMER.git@6683822c6210083e4ab0eecb4b6327e3c55f4c46
