name: Bug Report
description: Report something that is broken or incorrect
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Before you post this issue, please check the documentation:

        - [Pipeline usage documentation](https://github.com/bhargava-morampalli/rnamodbench/blob/dev/docs/usage.md)
        - [Pipeline output documentation](https://github.com/bhargava-morampalli/rnamodbench/blob/dev/docs/output.md)

  - type: textarea
    id: description
    attributes:
      label: Description of the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: command_used
    attributes:
      label: Command used and terminal output
      description: Steps to reproduce the behaviour. Please paste the command you used to launch the pipeline and the output from your terminal.
      render: console
      placeholder: |
        $ nextflow run ...

        Some output where something broke

  - type: textarea
    id: files
    attributes:
      label: Relevant files
      description: |
        Please drag and drop the relevant files here. Create a `.zip` archive if the extension is not allowed.
        Your verbose log file `.nextflow.log` is often useful _(this is a hidden file in the directory where you launched the pipeline)_ as well as custom Nextflow configuration files.

  - type: textarea
    id: system
    attributes:
      label: System information
      description: |
        * Nextflow version _(eg. 23.04.1)_
        * Hardware _(eg. HPC, Desktop, Cloud)_
        * Executor _(eg. Slurm, PBS, local)_
        * Container engine: _(eg. Docker, Singularity, Conda, Podman, Apptainer)_
        * OS _(eg. Ubuntu Linux 22.04, macOS 14.2, Windows 11)_
        * Version of bhargava-morampalli/rnamodbench _(eg. 1.0.0, 1.0.1)_
