channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python>=3.8
  - conda-forge::numpy
  - conda-forge::scipy
  - conda-forge::pandas<2.0
  - bioconda::pysam
  - bioconda::samtools=1.17
  - conda-forge::h5py
  - conda-forge::statsmodels
  - conda-forge::joblib
  - conda-forge::click
  - conda-forge::git
  - conda-forge::pip
  - pip:
      - git+https://github.com/bartongroup/differr_nanopore_DRS.git@a554d00c894d76cd4e91e2312cf88d611b0af3d2
