---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "samtools_view"
description: View and convert SAM/BAM/CRAM files
keywords:
  - view
  - bam
  - sam
  - cram
  - convert
tools:
  - samtools:
      description: |
        SAMtools is a suite of programs for interacting with high-throughput sequencing data.
        It consists of three separate repositories: Samtools (reading/writing/editing/indexing/viewing SAM/BAM/CRAM format), 
        BCFtools (reading/writing BCF2/VCF/gVCF files and calling/filtering/summarising SNP and short indel sequence variants),
        and HTSlib (a C library for reading/writing high-throughput sequencing data formats).
      homepage: http://www.htslib.org/
      documentation: https://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - sam:
        type: file
        description: sam file
output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - '*.bam':
          type: file
          description: BAM/CRAM/SAM file
          pattern: "*.{bam,cram,sam}"
  versions_samtools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - (samtools --version 2>/dev/null || echo unknown) | head -n 1 | cut -d " " -f 2:
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - (samtools --version 2>/dev/null || echo unknown) | head -n 1 | cut -d " " -f 2:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@bhargava-morampalli"
maintainers:
  - "@bhargava-morampalli"
