---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "extract_mapped_reads"
description: Extract mapped reads from SAM/BAM files and convert to FASTQ format
keywords:
  - extract
  - mapped
  - reads
  - fastq
  - samtools
  - nanopore
tools:
  - samtools:
      description: |
        SAMtools is a suite of programs for interacting with high-throughput sequencing data.
        It consists of three separate repositories: Samtools (reading/writing/editing/indexing/viewing SAM/BAM/CRAM format),
        BCFtools (reading/writing BCF2/VCF/gVCF files and calling/filtering/summarising SNP and short indel sequence variants),
        and HTSlib (a C library for reading/writing high-throughput sequencing data formats).
      homepage: http://www.htslib.org/
      documentation: https://www.htslib.org/doc/samtools-fastq.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - sam:
        type: file
        description: SAM/BAM file containing aligned reads
        pattern: "*.{sam,bam}"
output:
  fastq:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - '*.fastq':
          type: file
          description: FASTQ file containing only mapped reads
          pattern: "*.fastq"
  versions_samtools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - (samtools --version 2>/dev/null || echo unknown) | head -n 1 | cut -d " " -f 2:
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - (samtools --version 2>/dev/null || echo unknown) | head -n 1 | cut -d " " -f 2:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@bhargava-morampalli"
maintainers:
  - "@bhargava-morampalli"
