name: "f5c_eventalign"
description: Align nanopore raw signal events to reference k-mers for methylation detection
keywords:
  - eventalign
  - nanopore
  - fast5
  - f5c
  - methylation
  - signal
  - alignment
tools:
  - f5c:
      description: |
        f5c is an optimised re-implementation of the call-methylation and eventalign
        modules in Nanopolish. Given a set of basecalled Nanopore reads and the raw signals,
        f5c call-methylation detects methylated cytosine and f5c eventalign aligns raw
        nanopore signals (events) to the reference k-mers. f5c supports the latest nanopore
        R10.4.1 chemistry.
      homepage: https://github.com/hasindu2008/f5c
      documentation: https://hasindu2008.github.io/f5c/docs/commands
      tool_dev_url: https://github.com/hasindu2008/f5c
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - fastq:
      type: file
      description: Basecalled FASTQ file from Oxford Nanopore sequencing
      pattern: "*.{fastq,fq,fastq.gz,fq.gz}"
  - fastq_idx:
      type: file
      description: f5c index file generated by f5c index
      pattern: "*.index"
  - readdb:
      type: file
      description: f5c read database file generated by f5c index
      pattern: "*.index.readdb"
  - gzi:
      type: file
      description: BGZF index file generated by f5c index
      pattern: "*.index.gzi"
  - fai:
      type: file
      description: FASTA index file generated by f5c index
      pattern: "*.index.fai"
  - bam:
      type: file
      description: Sorted and aligned BAM file
      pattern: "*.bam"
  - bai:
      type: file
      description: BAM index file
      pattern: "*.bai"
  - fast5:
      type: directory
      description: Directory containing FAST5 files from Oxford Nanopore sequencing
      pattern: "*/"
  - reference:
      type: file
      description: Reference genome in FASTA format
      pattern: "*.{fasta,fa,fna}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - eventalign:
      type: file
      description: Tab-delimited eventalign output with raw signal alignment information
      pattern: "*_eventalign.txt"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@bhargava-morampalli"
