---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "generate_error_report"
description: Generates an HTML and CSV error summary report from pipeline execution
  logs
keywords:
  - error
  - report
  - summary
  - logging
tools:
  - python:
      description: |
        Python script that parses Nextflow execution logs and generates
        a summary report of failed processes and error messages.
      homepage: https://www.python.org/
      documentation: https://docs.python.org/
      licence: ["PSF-2.0"]

input:
  - - run_dir:
        type: string
        description: run_dir value
output:
  process_status:
    - - process_status.tsv:
          type: file
          description: process_status output file
          pattern: '*'
  log_events:
    - - log_events.tsv:
          type: file
          description: log_events output file
          pattern: '*'
  availability:
    - - tool_availability_per_run.tsv:
          type: file
          description: availability output file
          pattern: '*'
  html:
    - - error_summary.html:
          type: file
          description: html output file
          pattern: '*'
  csv:
    - - error_summary.csv:
          type: file
          description: csv output file
          pattern: '*'
  versions_python:
    - - ${task.process}:
          type: string
          description: The name of the process
      - python:
          type: string
          description: The name of the tool
      - python --version 2>&1 | sed 's/Python //' || echo unknown:
          type: eval
          description: The expression to obtain the version of the tool
  versions_pandas:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pandas:
          type: string
          description: The name of the tool
      - python -c 'import pandas; print(pandas.__version__)' 2>/dev/null || echo unknown:
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - python:
          type: string
          description: The name of the tool
      - python --version 2>&1 | sed 's/Python //' || echo unknown:
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - pandas:
          type: string
          description: The name of the tool
      - python -c 'import pandas; print(pandas.__version__)' 2>/dev/null || echo unknown:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@bmorampa"
maintainers:
  - "@bmorampa"
